# Generated by Django 4.0.5 on 2022-07-08 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('social_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=11)),
                ('contact_email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=15)),
                ('city_name', models.CharField(max_length=10)),
                ('member_creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=20)),
                ('floor_rooms', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=150)),
                ('release_year', models.IntegerField()),
                ('director', models.CharField(max_length=100)),
                ('movie_plot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('mobile_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=20)),
                ('floor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('expense_category', models.CharField(max_length=20)),
                ('expense_item', models.CharField(max_length=25)),
                ('expense_price', models.IntegerField()),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('booking_source', models.CharField(max_length=15)),
                ('booking_reason', models.CharField(max_length=15)),
                ('payment_type', models.CharField(max_length=15)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('total_amount', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('pending_amount', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.customer')),
            ],
        ),
    ]
