# Generated by Django 4.0.5 on 2022-08-22 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_source', models.CharField(choices=[('Booking.com', 'Booking.com')], max_length=15)),
                ('booking_reason', models.CharField(choices=[('Tourism', 'Tourism')], max_length=15)),
                ('customer', models.CharField(max_length=20)),
                ('accompanied_with', models.CharField(blank=True, max_length=20, null=True)),
                ('total_guests', models.IntegerField(default=1)),
                ('from_date', models.DateTimeField(default=datetime.datetime.now)),
                ('to_date', models.DateTimeField(default=datetime.datetime.now)),
                ('total_amount', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('floor_id', models.AutoField(primary_key=True, serialize=False)),
                ('floor_name', models.CharField(max_length=20)),
                ('floor_rooms', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=20)),
                ('floor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.floor')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLine',
            fields=[
                ('line_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('US', 'Cash'), ('EGP', 'egypt')], max_length=10)),
                ('rate', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('total', models.IntegerField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.paymentline')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('expense_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.category')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.floor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.item')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('social_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('contact_number', models.CharField(max_length=11)),
                ('contact_email', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('member_creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.country')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.country'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_system.room'),
        ),
    ]
