# Generated by Django 4.0.5 on 2022-07-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
