# Generated by Django 4.0.5 on 2022-07-08 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_alter_booking_from_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
