# Generated by Django 4.0.5 on 2022-07-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0003_alter_booking_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.CharField(max_length=30),
        ),
    ]
