# Generated by Django 4.0.5 on 2022-07-11 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0004_alter_booking_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='member_creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
