# Generated by Django 4.0.5 on 2022-07-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0005_alter_customer_member_creation_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
