# Generated by Django 4.0.5 on 2022-07-14 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0006_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
