# Generated by Django 4.0.5 on 2022-07-18 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0008_alter_expense_expense_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pending_amount',
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_category',
            field=models.CharField(choices=[('احتياحات', 'احتياجات'), ('خدمات', 'خدمات'), ('تجديجات', 'تجديدات'), ('راتب', 'راتب'), ('صيانه', 'صيانه'), ('عموله', 'عموله'), ('مصاريف مكتبيه', 'مصاريف مكتبيه'), ('معدات تنظيف', 'معدات تنظيف'), ('نفقات تشغيل', 'نفقات تشغيل')], max_length=20),
        ),
    ]
