# Generated by Django 4.0.5 on 2022-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0009_remove_booking_pending_amount_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
